// Pure generators — baseSkills passed in (no import of skills.json).
import { ROLE_META, roleSlug, commandsFor } from './roles.js';

const MCP_SERVERS = {
  figma: { command: 'npx', args: ['-y', 'figma-developer-mcp', '--stdio'], env: { FIGMA_API_KEY: '${input:figma_key}' } },
  playwright: { command: 'npx', args: ['-y', '@playwright/mcp'] },
};

export function renderMcpJson(mcp) {
  const servers = {};
  if (mcp?.figma) servers.figma = MCP_SERVERS.figma;
  if (mcp?.playwright) servers.playwright = MCP_SERVERS.playwright;
  return JSON.stringify({ servers }, null, 2);
}

export function renderRoleSkill(role, selectedSkills) {
  const meta = ROLE_META[role];
  const slug = roleSlug(role);
  return `---
name: ${slug}
version: 0.1.0
snapshotPath: .agents/cold-start/snapshots/${slug}.snapshot.md
snapshotVersion: 0.1.0
driftPolicyPath: .agents/evals/rubrics/${slug}.yaml
---

# ${meta.title} — Role Skill

## Scope
${meta.scope}

## Must rules
${meta.must.map((m) => `- ${m}`).join('\n')}

## Never do
${meta.never.map((n) => `- ${n}`).join('\n')}

## Verification
${meta.verification}

## Playbooks
${(selectedSkills || []).map((s) => `- assets/${s}.md`).join('\n') || '- (none selected)'}
`;
}

export function renderRoleRubric(role) {
  const slug = roleSlug(role);
  return `skill: ${slug}
criteria:
  - id: rule-adherence
    description: "Output follows the role skill's Must rules and violates no Never rules"
    weight: 1.0
driftPolicy:
  windowDays: 7
  minRunsForTrend: 5
  criterionDriftThreshold: 0.15
  skillDriftThreshold: 0.10
  baselineStrategy: first_N_runs
  baselineRuns: 10
  aggregation: median
  ciFailConsecutiveWindows: 2
  reviewTriggerAction: log_only
  reviewWorkflow: skill-review
`;
}

export function renderRoleSubagent(role) {
  const meta = ROLE_META[role];
  const slug = roleSlug(role);
  return `---
name: ${slug}
domain: ${slug}
skill: .agents/skills/${slug}/SKILL.md
---

# ${meta.title} — Subagent (canonical definition)

> Seed for the harness Multi-Agent system, which is INACTIVE until this project has a
> real multi-agent workflow. Do not project this file to any vendor format until that
> system activates (see the systems status in .agents/REGISTRY.md).

Load \`.agents/skills/${slug}/SKILL.md\` before any ${meta.title} work. Stay within the
role's scope; escalate cross-role decisions to the orchestrating session. Follow the
role workflows in \`.agents/workflows/${slug}/\`.
`;
}

export function renderRoleWorkflow(role, cmd) {
  const meta = ROLE_META[role];
  const slug = roleSlug(role);
  const action = cmd.replace('specforge-', '');
  return `# ${cmd} — ${meta.title} workflow

Run the **${action}** step for the ${meta.title} role.

## Steps
1. Load \`.agents/skills/${slug}/SKILL.md\` (via ROUTING) and the relevant playbooks
   from its \`assets/\`.
2. If the task touches a primary entity, load its spec from \`.agents/specs/\`.
3. Produce the ${action} output, traceable to the spec or story it serves.
4. Record follow-up work as tasks through the spec-first pipeline — never as silent
   notes.

## Guardrails
- Specifications are the source of truth; never invent requirements — ask.
- Stay within the ${meta.title} role's scope (see the skill's Never do rules).
- No secrets in any output.
`;
}

export function renderRolePrompt(role, cmd) {
  const slug = roleSlug(role);
  return `---
agent: agent
description: ${ROLE_META[role].title} command ${cmd} (SpecDD Harness role pack)
---

# /${cmd}

Follow the workflow at \`.agents/workflows/${slug}/${cmd}.md\`.
Read the root \`AGENTS.md\` primer first if you have not already this session.
`;
}

export function renderInstallTasks(input, today) {
  const pad3 = (n) => String(n).padStart(3, '0');
  let i = 0;
  const rows = (input.roles || []).flatMap((role) => {
    const slug = roleSlug(role);
    const meta = ROLE_META[role];
    return [
      `- [ ] R${pad3(++i)} Add ROUTING row: \`| ${meta.title} work | .agents/skills/${slug}/SKILL.md | role workflows in .agents/workflows/${slug}/ |\``,
      `- [ ] R${pad3(++i)} Add REGISTRY entries for the ${slug} skill, rubric, workflows and subagent (Multi-Agent system stays inactive)`,
      `- [ ] R${pad3(++i)} Add budget-manifest class '${meta.title} work' with artifacts [.agents/orchestration/ROUTING.md, .agents/skills/${slug}/SKILL.md]`,
    ];
  });
  return `---
feature: role-pack-install
status: draft
createdAt: ${today}
---

# Tasks — Role Pack Install

Pre-generated by the SpecForge wizard. A human must approve this file BEFORE the
agent wires anything. The pack never modifies existing harness files by itself.

## Phase 1 — Wire the roles
${rows.join('\n')}
- [ ] R${pad3(++i)} If any addition would push the root AGENTS.md primer past 40 lines, decompose the classification table instead of exceeding the limit
- [ ] R${pad3(++i)} Run \`pwsh .agents/scripts/generate-snapshots.ps1 -Scaffold\` for the new role skills and fill their compressed sections

## Phase 2 — Verify (done gate)
- [ ] C001 \`pwsh .agents/scripts/validate-spec.ps1\` exits 0
- [ ] C002 \`pwsh .agents/scripts/validate-budget.ps1\` exits 0
- [ ] C003 \`pwsh .agents/scripts/generate-snapshots.ps1 -Check\` exits 0
`;
}

export function renderPackReport(input, skipped, today) {
  const h = input.harness || {};
  const targetLine = (input.targetPaths || []).length
    ? (h.specdd
      ? 'SpecDD Harness detected in the target project — this pack extends it.'
      : h.legacy
        ? 'A legacy (non-SpecDD) harness was detected in the target. Migrate it first with the SpecDD wizard (Brownfield scenario) — this pack assumes the SpecDD Harness layout.'
        : 'No harness detected in the target project. Generate one first with the SpecDD wizard; this pack plugs into it.')
    : 'No target project was ingested — standard pack with canonical paths.';
  const rolesBlock = (input.roles || [])
    .map((r) => `- ${ROLE_META[r].title}: role skill + ${(input.skillsByRole?.[r] || []).length} playbook(s) · workflows: ${commandsFor(r, input).join(', ')}`)
    .join('\n');
  const skippedBlock = skipped.length
    ? `${skipped.map((p) => `- ${p}`).join('\n')}\n\nThese pack files were NOT written because they already exist in the target project.`
    : '- (none)';
  const installSkipped = skipped.includes('.agents/specs/tasks/role-pack-install.tasks.md');
  const kickoffLine = installSkipped
    ? `The target already contains .agents/specs/tasks/role-pack-install.tasks.md, so this pack did not overwrite it. Review the existing file (it may be a stale draft) and re-generate the pack after resolving it if needed. The Multi-Agent system stays inactive.`
    : `Get the human's approval on \`.agents/specs/tasks/role-pack-install.tasks.md\`, then
execute it to wire ROUTING/REGISTRY/budget. The Multi-Agent system stays inactive.`;
  return `# Role Pack Report

Generated by the SpecForge wizard on ${today}. Everything ran in the browser; no
file left the machine.

## Target
${targetLine}

## Roles in this pack
${rolesBlock}

## Kickoff (first agent session)
${kickoffLine}

## Skipped pack files (already exist in the target)
${skippedBlock}
`;
}

const REPORT_PATH = 'context/role-pack-report.md';

export function generatePack(baseSkills, input, today = new Date().toISOString().slice(0, 10)) {
  const files = {};
  const roles = input.roles || [];
  const hasCopilot = (input.tools || []).includes('GitHub Copilot');

  for (const role of roles) {
    const slug = roleSlug(role);
    const selected = input.skillsByRole?.[role] || [];
    files[`.agents/skills/${slug}/SKILL.md`] = renderRoleSkill(role, selected);
    for (const s of selected) {
      if (baseSkills[s]) files[`.agents/skills/${slug}/assets/${s}.md`] = baseSkills[s];
    }
    files[`.agents/evals/rubrics/${slug}.yaml`] = renderRoleRubric(role);
    for (const cmd of commandsFor(role, input)) {
      files[`.agents/workflows/${slug}/${cmd}.md`] = renderRoleWorkflow(role, cmd);
      if (hasCopilot) files[`.github/prompts/${cmd}.prompt.md`] = renderRolePrompt(role, cmd);
    }
    files[`.agents/subagents/${slug}.agent.md`] = renderRoleSubagent(role);
  }

  files['.agents/specs/tasks/role-pack-install.tasks.md'] = renderInstallTasks(input, today);

  const mcp = {
    figma: roles.includes('UX') && !!input.ux?.figmaEnabled,
    playwright: roles.includes('QA') && input.qa?.approach && input.qa.approach !== 'manual',
  };
  if (mcp.figma || mcp.playwright) files['.vscode/mcp.json'] = renderMcpJson(mcp);

  const existing = new Set(input.targetPaths || []);
  const skipped = Object.keys(files).filter((p) => existing.has(p) && p !== REPORT_PATH).sort();
  for (const p of skipped) delete files[p];
  files[REPORT_PATH] = renderPackReport(input, skipped, today);
  return { files, skipped };
}
