// Pure generators — baseSkills passed in (no import of skills.json).

const MCP_SERVERS = {
  figma: { command: 'npx', args: ['-y', 'figma-developer-mcp', '--stdio'], env: { FIGMA_API_KEY: '${input:figma_key}' } },
  playwright: { command: 'npx', args: ['-y', '@playwright/mcp'] },
};

export function renderMcpJson(mcp) {
  const servers = {};
  if (mcp?.figma) servers.figma = MCP_SERVERS.figma;
  if (mcp?.playwright) servers.playwright = MCP_SERVERS.playwright;
  return JSON.stringify({ servers }, null, 2);
}

export const PERSONA_PROMPTS = {
  BA: ['specforge-requirements', 'specforge-stories', 'specforge-new-feature', 'specforge-reset-feature'],
  QA: ['specforge-testcases', 'specforge-validate'],
  Dev: ['specforge-implement', 'specforge-review', 'specforge-createpr'],
  UX: ['specforge-uxflow', 'specforge-screenspec', 'specforge-copy'],
};

export function promptsFor(input) {
  const base = [...(PERSONA_PROMPTS[input.persona] || [])];
  if (input.persona === 'QA' && input.qa?.approach && input.qa.approach !== 'manual') base.push('specforge-playwright');
  if (input.persona === 'UX' && input.ux?.figmaEnabled) base.push('specforge-setupfigmamcp');
  return base;
}

export function renderReadme(input) {
  return `# ${input.project?.name || 'Scaffold'} — specforge (${input.persona})

Feature: **${input.project?.featureTitle || ''}**

Generated by specforge-kit for the **${input.persona}** persona.
Primary agent: ${input.agent?.primary || 'GitHub Copilot'}.

Run the persona commands from Copilot Chat: ${promptsFor(input).map((c) => `\`/${c}\``).join(', ')}.
`;
}

export function renderCopilotInstructions(input) {
  return `# Copilot Instructions — ${input.project?.name || 'Scaffold'} (${input.persona})

Primary agent: **${input.agent?.primary || 'GitHub Copilot'}** (model: ${input.agent?.model || 'default'}).
Persona: **${input.persona}**. Data classification: ${input.security?.classification || 'internal'}.

Read \`context/\` and \`.github/instructions/\` before acting. Never commit secrets.
`;
}

export function renderPersonaInstructions(input) {
  return `---
applyTo: "all"
description: specforge ${input.persona} persona guardrails
---

# specforge ${input.persona} Instructions

## Role
Act as a ${input.persona} following the specforge flow for feature "${input.project?.featureTitle || ''}".

## Guidelines
- Use the selected skills in \`skills/\` as playbooks.
- Keep outputs traceable to the feature context in \`context/\`.
- Never invent requirements; ask for clarification.

## Anti-patterns
- Producing work outside the ${input.persona} role.
- Committing secrets or real credentials.
`;
}

export function renderPrompt(cmd, input) {
  return `---
agent: agent
description: specforge ${input.persona} command ${cmd}
---

# /${cmd}

Run the ${cmd.replace('specforge-', '')} step for the **${input.persona}** persona on feature
"${input.project?.featureTitle || ''}".

## Steps
1. Read \`context/${input.project?.featureSlug || 'feature'}.md\` and \`.github/instructions/specforge-${input.persona.toLowerCase()}.instructions.md\`.
2. Apply the relevant skill(s) from \`skills/\`.
3. Write the output to the appropriate location (stories/, tests/, src/, or docs/).

## Guardrails
- Specifications and context are the source of truth.
- No secrets in output.
`;
}

export function generateFiles(baseSkills, input) {
  const out = {};
  out['README.md'] = renderReadme(input);
  out['.github/copilot-instructions.md'] = renderCopilotInstructions(input);
  out[`.github/instructions/specforge-${input.persona.toLowerCase()}.instructions.md`] = renderPersonaInstructions(input);
  for (const cmd of promptsFor(input)) {
    out[`.github/prompts/${cmd}.prompt.md`] = renderPrompt(cmd, input);
  }
  const slug = input.project?.featureSlug || 'feature';
  out[`context/${slug}.md`] = `# Context: ${input.project?.featureTitle || slug}\n\n${input.context?.text || ''}\n`;
  for (const s of input.skills || []) {
    if (baseSkills[s]) out[`skills/${s}.md`] = baseSkills[s];
  }
  if (input.mcp?.figma || input.mcp?.playwright) {
    out['.vscode/mcp.json'] = renderMcpJson(input.mcp);
  }
  return out;
}
