// Pure generators — baseSkills passed in (no import of skills.json).
import { ROLE_META, roleSlug, commandsFor } from './roles.js';

const MCP_SERVERS = {
  figma: { command: 'npx', args: ['-y', 'figma-developer-mcp', '--stdio'], env: { FIGMA_API_KEY: '${input:figma_key}' } },
  playwright: { command: 'npx', args: ['-y', '@playwright/mcp'] },
};

export function renderMcpJson(mcp) {
  const servers = {};
  if (mcp?.figma) servers.figma = MCP_SERVERS.figma;
  if (mcp?.playwright) servers.playwright = MCP_SERVERS.playwright;
  return JSON.stringify({ servers }, null, 2);
}

export const PERSONA_PROMPTS = {
  BA: ['specforge-requirements', 'specforge-stories', 'specforge-new-feature', 'specforge-reset-feature'],
  QA: ['specforge-testcases', 'specforge-validate'],
  Dev: ['specforge-implement', 'specforge-review', 'specforge-createpr'],
  UX: ['specforge-uxflow', 'specforge-screenspec', 'specforge-copy'],
};

export function promptsFor(input) {
  const base = [...(PERSONA_PROMPTS[input.persona] || [])];
  if (input.persona === 'QA' && input.qa?.approach && input.qa.approach !== 'manual') base.push('specforge-playwright');
  if (input.persona === 'UX' && input.ux?.figmaEnabled) base.push('specforge-setupfigmamcp');
  return base;
}

export function renderReadme(input) {
  return `# ${input.project?.name || 'Scaffold'} — specforge (${input.persona})

Feature: **${input.project?.featureTitle || ''}**

Generated by specforge-kit for the **${input.persona}** persona.
Primary agent: ${input.agent?.primary || 'GitHub Copilot'}.

Run the persona commands from Copilot Chat: ${promptsFor(input).map((c) => `\`/${c}\``).join(', ')}.
`;
}

export function renderCopilotInstructions(input) {
  return `# Copilot Instructions — ${input.project?.name || 'Scaffold'} (${input.persona})

Primary agent: **${input.agent?.primary || 'GitHub Copilot'}** (model: ${input.agent?.model || 'default'}).
Persona: **${input.persona}**. Data classification: ${input.security?.classification || 'internal'}.

Read \`context/\` and \`.github/instructions/\` before acting. Never commit secrets.
`;
}

export function renderPersonaInstructions(input) {
  return `---
applyTo: "all"
description: specforge ${input.persona} persona guardrails
---

# specforge ${input.persona} Instructions

## Role
Act as a ${input.persona} following the specforge flow for feature "${input.project?.featureTitle || ''}".

## Guidelines
- Use the selected skills in \`skills/\` as playbooks.
- Keep outputs traceable to the feature context in \`context/\`.
- Never invent requirements; ask for clarification.

## Anti-patterns
- Producing work outside the ${input.persona} role.
- Committing secrets or real credentials.
`;
}

export function renderPrompt(cmd, input) {
  return `---
agent: agent
description: specforge ${input.persona} command ${cmd}
---

# /${cmd}

Run the ${cmd.replace('specforge-', '')} step for the **${input.persona}** persona on feature
"${input.project?.featureTitle || ''}".

## Steps
1. Read \`context/${input.project?.featureSlug || 'feature'}.md\` and \`.github/instructions/specforge-${input.persona.toLowerCase()}.instructions.md\`.
2. Apply the relevant skill(s) from \`skills/\`.
3. Write the output to the appropriate location (stories/, tests/, src/, or docs/).

## Guardrails
- Specifications and context are the source of truth.
- No secrets in output.
`;
}

export function generateFiles(baseSkills, input) {
  const out = {};
  out['README.md'] = renderReadme(input);
  out['.github/copilot-instructions.md'] = renderCopilotInstructions(input);
  out[`.github/instructions/specforge-${input.persona.toLowerCase()}.instructions.md`] = renderPersonaInstructions(input);
  for (const cmd of promptsFor(input)) {
    out[`.github/prompts/${cmd}.prompt.md`] = renderPrompt(cmd, input);
  }
  const slug = input.project?.featureSlug || 'feature';
  out[`context/${slug}.md`] = `# Context: ${input.project?.featureTitle || slug}\n\n${input.context?.text || ''}\n`;
  for (const s of input.skills || []) {
    if (baseSkills[s]) out[`skills/${s}.md`] = baseSkills[s];
  }
  if (input.mcp?.figma || input.mcp?.playwright) {
    out['.vscode/mcp.json'] = renderMcpJson(input.mcp);
  }
  return out;
}

export function renderRoleSkill(role, selectedSkills) {
  const meta = ROLE_META[role];
  const slug = roleSlug(role);
  return `---
name: ${slug}
version: 0.1.0
snapshotPath: .agents/cold-start/snapshots/${slug}.snapshot.md
snapshotVersion: 0.1.0
driftPolicyPath: .agents/evals/rubrics/${slug}.yaml
---

# ${meta.title} — Role Skill

## Scope
${meta.scope}

## Must rules
${meta.must.map((m) => `- ${m}`).join('\n')}

## Never do
${meta.never.map((n) => `- ${n}`).join('\n')}

## Verification
${meta.verification}

## Playbooks
${(selectedSkills || []).map((s) => `- assets/${s}.md`).join('\n') || '- (none selected)'}
`;
}

export function renderRoleRubric(role) {
  const slug = roleSlug(role);
  return `skill: ${slug}
criteria:
  - id: rule-adherence
    description: "Output follows the role skill's Must rules and violates no Never rules"
    weight: 1.0
driftPolicy:
  windowDays: 7
  minRunsForTrend: 5
  criterionDriftThreshold: 0.15
  skillDriftThreshold: 0.10
  baselineStrategy: first_N_runs
  baselineRuns: 10
  aggregation: median
  ciFailConsecutiveWindows: 2
  reviewTriggerAction: log_only
  reviewWorkflow: skill-review
`;
}

export function renderRoleSubagent(role) {
  const meta = ROLE_META[role];
  const slug = roleSlug(role);
  return `---
name: ${slug}
domain: ${slug}
skill: .agents/skills/${slug}/SKILL.md
---

# ${meta.title} — Subagent (canonical definition)

> Seed for the harness Multi-Agent system, which is INACTIVE until this project has a
> real multi-agent workflow. Do not project this file to any vendor format until that
> system activates (see the systems status in .agents/REGISTRY.md).

Load \`.agents/skills/${slug}/SKILL.md\` before any ${meta.title} work. Stay within the
role's scope; escalate cross-role decisions to the orchestrating session. Follow the
role workflows in \`.agents/workflows/${slug}/\`.
`;
}

export function renderRoleWorkflow(role, cmd) {
  const meta = ROLE_META[role];
  const slug = roleSlug(role);
  const action = cmd.replace('specforge-', '');
  return `# ${cmd} — ${meta.title} workflow

Run the **${action}** step for the ${meta.title} role.

## Steps
1. Load \`.agents/skills/${slug}/SKILL.md\` (via ROUTING) and the relevant playbooks
   from its \`assets/\`.
2. If the task touches a primary entity, load its spec from \`.agents/specs/\`.
3. Produce the ${action} output, traceable to the spec or story it serves.
4. Record follow-up work as tasks through the spec-first pipeline — never as silent
   notes.

## Guardrails
- Specifications are the source of truth; never invent requirements — ask.
- Stay within the ${meta.title} role's scope (see the skill's Never do rules).
- No secrets in any output.
`;
}

export function renderRolePrompt(role, cmd) {
  const slug = roleSlug(role);
  return `---
agent: agent
description: ${ROLE_META[role].title} command ${cmd} (SpecDD Harness role pack)
---

# /${cmd}

Follow the workflow at \`.agents/workflows/${slug}/${cmd}.md\`.
Read the root \`AGENTS.md\` primer first if you have not already this session.
`;
}

export function renderInstallTasks(input, today) {
  const pad3 = (n) => String(n).padStart(3, '0');
  let i = 0;
  const rows = (input.roles || []).flatMap((role) => {
    const slug = roleSlug(role);
    const meta = ROLE_META[role];
    return [
      `- [ ] R${pad3(++i)} Add ROUTING row: \`| ${meta.title} work | .agents/skills/${slug}/SKILL.md | role workflows in .agents/workflows/${slug}/ |\``,
      `- [ ] R${pad3(++i)} Add REGISTRY entries for the ${slug} skill, rubric, workflows and subagent (Multi-Agent system stays inactive)`,
      `- [ ] R${pad3(++i)} Add budget-manifest class '${meta.title} work' with artifacts [.agents/orchestration/ROUTING.md, .agents/skills/${slug}/SKILL.md]`,
    ];
  });
  return `---
feature: role-pack-install
status: draft
createdAt: ${today}
---

# Tasks — Role Pack Install

Pre-generated by the SpecForge wizard. A human must approve this file BEFORE the
agent wires anything. The pack never modifies existing harness files by itself.

## Phase 1 — Wire the roles
${rows.join('\n')}
- [ ] R${pad3(++i)} If any addition would push the root AGENTS.md primer past 40 lines, decompose the classification table instead of exceeding the limit

## Phase 2 — Verify (done gate)
- [ ] C001 \`pwsh .agents/scripts/validate-spec.ps1\` exits 0
- [ ] C002 \`pwsh .agents/scripts/validate-budget.ps1\` exits 0
`;
}

export function renderPackReport(input, skipped, today) {
  const h = input.harness || {};
  const targetLine = (input.targetPaths || []).length
    ? (h.specdd
      ? 'SpecDD Harness detected in the target project — this pack extends it.'
      : h.legacy
        ? 'A legacy (non-SpecDD) harness was detected in the target. Migrate it first with the SpecDD wizard (Brownfield scenario) — this pack assumes the SpecDD Harness layout.'
        : 'No harness detected in the target project. Generate one first with the SpecDD wizard; this pack plugs into it.')
    : 'No target project was ingested — standard pack with canonical paths.';
  const rolesBlock = (input.roles || [])
    .map((r) => `- ${ROLE_META[r].title}: role skill + ${(input.skillsByRole?.[r] || []).length} playbook(s) · workflows: ${commandsFor(r, input).join(', ')}`)
    .join('\n');
  const skippedBlock = skipped.length
    ? `${skipped.map((p) => `- ${p}`).join('\n')}\n\nThese pack files were NOT written because they already exist in the target project.`
    : '- (none)';
  return `# Role Pack Report

Generated by the SpecForge wizard on ${today}. Everything ran in the browser; no
file left the machine.

## Target
${targetLine}

## Roles in this pack
${rolesBlock}

## Kickoff (first agent session)
Get the human's approval on \`.agents/specs/tasks/role-pack-install.tasks.md\`, then
execute it to wire ROUTING/REGISTRY/budget. The Multi-Agent system stays inactive.

## Skipped pack files (already exist in the target)
${skippedBlock}
`;
}
