trigger:
  branches:
    include:
      - main
{{#if envDev}}
      - develop
{{/if}}

variables:
  - group: specdeploy-secrets

pool:
  vmImage: ubuntu-latest

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '20.x'
  - script: |
      npm ci
      {{app.buildCommand}}
    displayName: Build
  - task: AzureStaticWebApp@0
    inputs:
      app_location: /
      output_location: {{app.outputDir}}
{{#if api}}
      api_location: {{app.apiDir}}
{{/if}}
      skip_app_build: true
      azure_static_web_apps_api_token: $(AZURE_STATIC_WEB_APPS_API_TOKEN)
