const $=id=>document.getElementById(id);
let session,view,projectId,selected=null,timer=null,busy=false,dirty=false,role='ba';
const dirtyTargets=new Set();
function markDirty(target){if([...dirtyTargets].some(id=>id!==target))throw new Error('UNSAVED_CHANGES');dirty=true;dirtyTargets.add(target);for(const field of $('detail').querySelectorAll('input,textarea'))if(field.closest('[data-artifact]').dataset.artifact!==target)field.disabled=true;}
const labels={draft:'Borrador','under-review':'En revisión',approved:'Aprobado',active:'Activo',superseded:'Retirado',running:'Analizando',ready:'Propuesta para revisar',adopted:'Incorporada',discarded:'Descartada',cancelled:'Cancelada','needs-attention':'Necesita atención'};
const qaKinds={'test-scenario':'Escenario','test-case':'Caso de prueba','coverage-assessment':'Cobertura declarada','quality-risk':'Riesgo de calidad',defect:'Defecto evidenciado'};
const errors={STALE_STATE:'El proyecto cambió. Actualizá y revisá el contenido antes de repetir la acción.',BA_STALE_APPROVAL:'Cambió el contexto de la aprobación. Preparala nuevamente.',BA_STALE_REQUEST:'La propuesta pertenece a un contexto anterior. No se aplicó; descartala y solicitá un nuevo análisis.',BA_BLOCKED:'Hay preguntas o bloqueos pendientes. Revisalos antes de aprobar.',BA_DEPENDENCY_UNAPPROVED:'Primero revisá y aprobá las reglas o decisiones relacionadas.',BA_CRITERIA_REQUIRED:'Agregá al menos un criterio de aceptación antes de aprobar.',BA_QUESTION_OPEN:'La pregunta todavía no tiene respuesta humana.',RUNTIME_UNAVAILABLE:'El operador todavía no configuró un agente.',STALE_CONTEXT:'El contexto cambió durante el análisis. El borrador se conservó; solicitá otro análisis si corresponde.',RUNTIME_FAILED:'El agente no pudo completar la acción. No se cambió el requisito. Revisá la configuración con el operador.',INVALID_AGENT_OUTPUT:'La respuesta no cumplió el contrato. No se incorporó contenido.',TIMEOUT:'El análisis superó el tiempo permitido.',INTERRUPTED:'El servicio se interrumpió. No hubo reintento automático.',CANCELLED:'Análisis cancelado por el usuario.'};
errors.PROJECTION_APPROVED_REQUIREMENT_REQUIRED='Sólo un requisito con aprobación vigente puede proyectarse.';errors.PROJECTION_PENDING='Ya existe una propuesta SpecDD pendiente para este requisito.';errors.PROJECTION_STALE='Cambió el requisito, el grafo o el destino canónico. Prepará una nueva proyección.';errors.PROJECTION_STALE_APPROVAL='La aprobación no corresponde al subject exacto de esta proyección.';
function el(tag,content,className){const n=document.createElement(tag);if(content!==undefined)n.textContent=content;if(className)n.className=className;return n;}
function button(label,fn,secondary=false){const b=el('button',label,secondary?'secondary':'');b.type='button';b.addEventListener('click',()=>task(fn));return b;}
function field(parent,label,value='',tag='input'){const l=el('label',label),n=document.createElement(tag);n.value=value;l.append(n);parent.append(l);return n;}
function detail(title,content){const d=el('details'),s=el('summary',title);d.append(s,el('pre',content));return d;}
async function api(path,body){const res=await fetch(path,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json','x-specforge-csrf':session.csrf}:{},...(body?{body:JSON.stringify(body)}:{})});const data=await res.json();if(!res.ok)throw new Error(data.error);return data;}
function message(error){$('message').textContent=errors[error.message]??`No se completó la operación (${error.message}). Los cambios no se aplicaron. Podés actualizar para revisar el estado.`;}
errors.RUNTIME_PERMISSIONS_UNVERIFIED='No se pudieron verificar los permisos del agente. El análisis no se inició. Conservá el borrador y pedí al operador revisar el preflight; no hay reintento automático.';
Object.assign(errors,{QA_APPROVED_REQUIREMENT_REQUIRED:'QA sólo trabaja sobre requisitos aprobados con criterios.',QA_STALE_APPROVAL:'Cambió el artefacto o su grafo. Prepará nuevamente la aprobación.',QA_BLOCKED:'El artefacto QA tiene bloqueos pendientes.',QA_CRITERION_REFERENCE:'El artefacto referencia un criterio que ya no existe.',QA_DEFECT_EVIDENCE_REQUIRED:'Un defecto exige evidencia humana o de sistema con hash.',QA_PROPOSAL_NOT_READY:'La propuesta QA ya no está disponible.',QA_STALE_REQUEST:'La propuesta QA pertenece a un contexto anterior.',QA_CAPABILITY_UNAVAILABLE:'Este proyecto no tiene el dominio QA preparado.'});
async function task(fn){if(busy)return;busy=true;document.body.inert=true;document.body.setAttribute('aria-busy','true');$('message').textContent='';try{await fn();}catch(e){message(e);}finally{busy=false;document.body.inert=false;document.body.setAttribute('aria-busy','false');}}
const base=()=>`/api/projects/${encodeURIComponent(projectId)}`;
async function command(command,version=view.version){const target=command.op==='create'?'new':command.targetId;if([...dirtyTargets].some(id=>id!==target))throw new Error('UNSAVED_CHANGES');view=await api(`${base()}/command`,{version,command});render();}
async function refresh(){if(!projectId)return;if(dirty)throw new Error('UNSAVED_CHANGES');view=await api(base());render();}
function render(){
  dirty=false;dirtyTargets.clear();$('detail').dataset.artifact=selected??'new';
  clearTimeout(timer);$('operator').textContent=`Revisor local: ${view.operator} · identidad local declarada`;$('runtime').textContent=`Agente: ${view.runtime}`;
  $('context').replaceChildren(el('p',view.project.project.description||'Sin descripción de contexto.'),el('p',`Principios: ${view.project.project.principles.join(' · ')||'No declarados'}`),detail('Contexto preparado y procedencia',JSON.stringify(view.project,null,2)));
  if(role==='qa'){renderQA();return;}
  $('workspace-title').textContent='De la idea al requisito revisado.';$('role-badge').textContent='BA · local';$('list-title').textContent='Mis requisitos';$('new').hidden=false;
  $('workspace-notice').textContent='Las propuestas de IA son borradores. Vos decidís qué incorporar y qué aprobar. Las proyecciones SpecDD se guardan localmente; nada se escribe en un repositorio ni se publica.';
  const reqs=view.artifacts.filter(a=>a.type==='requirement');$('list').replaceChildren();
  for(const a of reqs){const b=button(`${a.title} · ${labels[a.status]}`,async()=>{if(dirty)throw new Error('UNSAVED_CHANGES');selected=a.id;render();},true);if(a.id===selected)b.classList.add('selected');$('list').append(b);}
  if(!reqs.length)$('list').append(el('p','Todavía no hay requisitos. Creá el primero a partir de un pedido real o del piloto sintético.','empty'));
  if(selected&&!view.artifacts.some(a=>a.id===selected))selected=null;
  $('detail').replaceChildren();if(selected)renderRequirement(view.artifacts.find(a=>a.id===selected));else renderNew();
  $('history').replaceChildren(...view.history.map(h=>el('p',`${new Date(h.event.at).toLocaleString()} · ${h.event.actor.id} · ${h.event.action} · versión ${h.version}`,'history-item')));
  const running=view.runs.some(r=>r.status==='running');
  $('new').disabled=running;$('projects').disabled=running;
  if(running)for(const n of $('detail').querySelectorAll('input,textarea,button'))if(n.textContent!=='Cancelar análisis')n.disabled=true;
  if(view.runs.some(r=>r.status==='running')){const poll=()=>{if(!busy)task(refresh);else timer=setTimeout(poll,250);};timer=setTimeout(poll,1500);}
}
function requirementFor(a){return view.artifacts.find(r=>a.relationships?.some(x=>x.target.artifactId===r.id)&&r.type==='requirement');}
function renderQA(){
  $('workspace-title').textContent='De la spec aprobada a evidencia QA revisable.';$('role-badge').textContent='QA · local';$('list-title').textContent='Specs relacionadas';$('new').hidden=true;
  $('workspace-notice').textContent='La cobertura mostrada es sólo de diseño declarado. El portal no ejecuta tests ni afirma resultados. Los defectos requieren evidencia con hash y toda aprobación es humana y exacta.';
  const reqs=view.artifacts.filter(a=>a.type==='requirement'&&['approved','active'].includes(a.status));$('list').replaceChildren();
  for(const a of reqs){const assigned=view.qa.assignments.includes(a.id),b=button(`${a.title} · ${assigned?'Asignada':'Disponible'}`,async()=>{if(dirty)throw new Error('UNSAVED_CHANGES');selected=a.id;render();},true);if(a.id===selected)b.classList.add('selected');$('list').append(b);}
  if(!reqs.length)$('list').append(el('p','No hay requisitos aprobados con criterios. QA no puede inventar el alcance.','empty'));
  if(selected&&!reqs.some(a=>a.id===selected))selected=reqs[0]?.id??null;$('detail').replaceChildren();
  if(selected)renderQASpec(reqs.find(a=>a.id===selected));else $('detail').append(el('p','Elegí una spec aprobada para preparar su diseño QA.','empty'));
  $('history').replaceChildren(...view.history.map(h=>el('p',`${new Date(h.event.at).toLocaleString()} · ${h.event.actor.id} · ${h.event.action} · versión ${h.version}`,'history-item')));
  const running=view.runs.some(r=>r.status==='running');$('projects').disabled=running;
  if(running)for(const n of $('detail').querySelectorAll('input,textarea,button,select'))if(n.textContent!=='Cancelar análisis')n.disabled=true;
  if(running){const poll=()=>{if(!busy)task(refresh);else timer=setTimeout(poll,250);};timer=setTimeout(poll,1500);}
}
function renderQASpec(req){const root=$('detail'),assigned=view.qa.assignments.includes(req.id),related=view.artifacts.filter(a=>a.ownerRole==='qa'&&requirementFor(a)?.id===req.id),cases=related.filter(a=>a.type==='test-case'),scenarios=related.filter(a=>a.type==='test-scenario'),risks=related.filter(a=>a.type==='quality-risk'),defects=related.filter(a=>a.type==='defect'),covered=new Set(cases.flatMap(c=>c.content.acceptanceCriterionIds));
  root.dataset.artifact=req.id;root.append(el('h2',req.title),el('p',`${assigned?'Asignada a QA':'Disponible para QA'} · requisito ${labels[req.status]} · revisión ${req.revision}`,'muted'),el('p',req.content.description));
  const criteriaList=el('div');for(const c of req.content.acceptanceCriteria){const item=el('div',undefined,'card criterion');item.dataset.criterionId=c.id;item.append(el('span',c.id,'qa-kind'),el('p',`Dado ${c.given}, cuando ${c.when}, entonces ${c.then}`));criteriaList.append(item);}const criteriaDetail=el('details');criteriaDetail.append(el('summary','Criterios aprobados e IDs'),criteriaList);root.append(criteriaDetail);
  const canonical=view.canonicalSpecs.filter(c=>c.source.artifact.artifactId===req.id).at(-1);if(canonical)root.append(detail(`SpecDD relacionada · ${canonical.path}`,canonical.content));
  const metrics=el('div',undefined,'coverage');for(const [n,v] of [['Criterios',req.content.acceptanceCriteria.length],['Cubiertos por casos',covered.size],['Escenarios',scenarios.length],['Defectos',defects.length]]){const m=el('div',undefined,'metric');m.append(el('strong',String(v)),el('span',n));metrics.append(m);}root.append(metrics,el('p','Cobertura de diseño declarada: no representa ejecución, pass/fail ni cobertura de código.','notice'));
  const actions=el('div',undefined,'actions');root.append(actions);if(!assigned)actions.append(button('Tomar spec para QA',async()=>command({op:'qa-assign',targetId:req.id})));
  actions.append(button('Recalcular cobertura declarada',async()=>command({op:'qa-refresh-coverage',targetId:req.id}),true));
  root.append(el('h3','Asistencia del agente'),el('p','El agente sólo propone gaps, escenarios, casos y riesgos. No ejecuta tests, no crea defectos y no aprueba.','muted'));
  const consentLabel=el('label',undefined,'check'),consent=document.createElement('input');consent.type='checkbox';consentLabel.append(consent,el('span','Autorizo enviar esta spec y su grafo al agente configurado para esta acción.'));root.append(consentLabel);
  const agentActions=el('div',undefined,'actions');root.append(agentActions);for(const [name,action] of [['Analizar spec aprobada','analyze-approved-spec'],['Sugerir escenarios','suggest-test-scenarios'],['Sugerir casos','suggest-test-cases'],['Evaluar riesgos','assess-quality-risks']]){const b=button(name,async()=>{if(!consent.checked)throw new Error('RUNTIME_CONSENT_REQUIRED');await api(`${base()}/runs`,{version:view.version,request:{targetId:req.id,action,consent:true}});await refresh();},true);b.disabled=!view.runtimeAvailable;agentActions.append(b);}
  if(!view.runtimeAvailable)root.append(el('p','Agente no configurado. El diseño, la evidencia y las aprobaciones locales siguen disponibles.','notice'));
  for(const run of view.runs.filter(r=>r.role==='qa'&&r.targetId===req.id))renderQARun(root,run);
  root.append(qaCreateForms(req));
  root.append(el('h3','Artefactos QA relacionados'));if(!related.length)root.append(el('p','Todavía no hay diseño QA registrado para esta spec.','empty'));
  for(const a of related)renderQAArtifact(root,a,req);
}
function qaCreateForms(req){const wrap=el('div');wrap.append(el('h3','Registrar diseño o evidencia QA'));
  const form=(title,type,build)=>{const d=el('details'),s=el('summary',title),body=el('div',undefined,'card');d.append(s,body);const name=field(body,'Título');build(body,name);wrap.append(d);return body;};
  form('Nuevo escenario','test-scenario',(b,name)=>{const objective=field(b,'Objetivo'),criteria=field(b,'IDs de criterios (separados por coma)'),tech=field(b,'Técnica','','select');for(const x of ['functional','boundary','negative','regression','exploratory'])tech.append(new Option(x,x));b.append(button('Guardar escenario',()=>command({op:'qa-create',targetId:req.id,type:'test-scenario',title:name.value,content:{objective:objective.value,acceptanceCriterionIds:csv(criteria.value),technique:tech.value}})));});
  form('Nuevo caso de prueba','test-case',(b,name)=>{const criteria=field(b,'IDs de criterios (separados por coma)'),pre=field(b,'Precondiciones (una por línea)','','textarea'),action=field(b,'Acción','','textarea'),expected=field(b,'Resultado esperado','','textarea'),level=field(b,'Nivel','','select');for(const x of ['manual','unit','integration','e2e'])level.append(new Option(x,x));b.append(button('Guardar caso',()=>command({op:'qa-create',targetId:req.id,type:'test-case',title:name.value,content:{acceptanceCriterionIds:csv(criteria.value),preconditions:lines(pre.value),steps:[{action:action.value,expected:expected.value}],level:level.value,automationStatus:level.value==='manual'?'manual':'candidate'}})));});
  form('Nuevo riesgo de calidad','quality-risk',(b,name)=>{const statement=field(b,'Riesgo','','textarea'),mitigation=field(b,'Mitigación','','textarea'),likelihood=field(b,'Probabilidad','','select'),impact=field(b,'Impacto','','select');for(const n of [likelihood,impact])for(const x of ['low','medium','high'])n.append(new Option(x,x));b.append(button('Guardar riesgo',()=>command({op:'qa-create',targetId:req.id,type:'quality-risk',title:name.value,content:{statement:statement.value,likelihood:likelihood.value,impact:impact.value,mitigation:mitigation.value}})));});
  form('Nuevo defecto con evidencia','defect',(b,name)=>{const observed=field(b,'Observado','','textarea'),expected=field(b,'Esperado','','textarea'),steps=field(b,'Pasos de reproducción (uno por línea)','','textarea'),locator=field(b,'Localizador de evidencia'),sha=field(b,'SHA-256 de evidencia'),severity=field(b,'Severidad','','select'),kind=field(b,'Tipo de evidencia','','select');for(const x of ['low','medium','high','critical'])severity.append(new Option(x,x));for(const x of ['log','screenshot','report','run'])kind.append(new Option(x,x));b.append(button('Guardar defecto evidenciado',()=>command({op:'qa-create',targetId:req.id,type:'defect',title:name.value,content:{severity:severity.value,observed:observed.value,expected:expected.value,reproductionSteps:lines(steps.value),evidence:[{kind:kind.value,locator:locator.value,sha256:sha.value}]}})));});return wrap;}
const csv=value=>[...new Set(value.split(',').map(x=>x.trim()).filter(Boolean))],lines=value=>value.split(/\r?\n/).map(x=>x.trim()).filter(Boolean);
function renderQAArtifact(root,a,req){const box=el('article',undefined,`card ${a.type==='defect'?'defect':a.type==='quality-risk'?'warning':''}`),approval=view.qa.approvals.filter(r=>r.targetId===a.id).at(-1);box.append(el('span',qaKinds[a.type]??a.type,'qa-kind'),el('h3',a.title),el('p',`${labels[a.status]} · revisión ${a.revision}${approval?approval.valid?' · aprobación vigente':' · aprobación fuera de vigencia':''}`,'muted'),detail('Contenido y trazabilidad',JSON.stringify({content:a.content,relationships:a.relationships,provenance:a.provenance},null,2)));
  if(a.type==='coverage-assessment'){const missing=a.content.entries.filter(e=>!e.testCaseRefs.length);box.append(el('p',missing.length?`${missing.length} criterio(s) sin caso declarado.`:'Todos los criterios tienen al menos un caso declarado.',missing.length?'notice':'muted'));}
  if(a.status==='draft')box.append(button('Solicitar revisión QA',async()=>command({op:'qa-request-review',targetId:a.id}),true));if(a.status==='under-review')box.append(button('Revisar aprobación QA',()=>openQAApproval(a.id),true));root.append(box);}
function renderQARun(root,run){const box=el('div',undefined,'card proposal');box.append(el('h3',labels[run.status]),el('p',`${run.action} · ${new Date(run.startedAt).toLocaleString()}`,'muted'));if(run.error)box.append(el('p',errors[run.error]??run.error));if(run.status==='running')box.append(button('Cancelar análisis',async()=>{await api(`${base()}/cancel`,{runId:run.id});await refresh();},true));
  if(run.proposal){const out=run.proposal.output,checks=[];box.append(el('p','Propuesta QA: seleccioná sólo diseño que quieras incorporar como borrador. Los gaps quedan visibles como observaciones.'));for(const g of out.gaps)box.append(el('p',`Gap: ${g.description}`));const candidates=[...out.scenarios.map(s=>({...s,text:`Escenario: ${s.objective}`})),...out.testCases.map(s=>({...s,text:`Caso: ${s.steps.map(x=>x.action).join(' / ')}`})),...out.risks.map(s=>({...s,text:`Riesgo: ${s.statement}`}))];for(const s of candidates){const l=el('label',undefined,'check'),c=document.createElement('input');c.type='checkbox';c.disabled=run.status!=='ready';l.append(c,el('span',s.text));box.append(l);checks.push({id:s.id,c});}if(run.status==='ready')box.append(button('Incorporar seleccionadas',()=>command({op:'qa-adopt',runId:run.id,selectedIds:checks.filter(s=>s.c.checked).map(s=>s.id)})),button('Descartar propuesta QA',()=>command({op:'qa-discard',runId:run.id}),true));}box.append(detail('Evidencia del turno',JSON.stringify({id:run.id,requestSha256:run.requestSha256,runtime:run.runtime},null,2)));root.append(box);}
async function openQAApproval(targetId){if(dirty)throw new Error('UNSAVED_CHANGES');let artifact=view.artifacts.find(a=>a.id===targetId);if(artifact.status==='draft'){await command({op:'qa-request-review',targetId});artifact=view.artifacts.find(a=>a.id===targetId);}const prepared=await api(`${base()}/qa-approval?target=${encodeURIComponent(targetId)}`);$('approval-title').textContent='Revisar aprobación QA exacta';$('approval-note').textContent='La aprobación cubre el artefacto y grafo exactos. No ejecuta tests, publica ni modifica repositorios.';$('approval-content').replaceChildren(el('h3',artifact.title),el('p',`${qaKinds[artifact.type]} · revisión ${artifact.revision} · revisor: ${view.operator}`),el('pre',JSON.stringify(artifact.content,null,2)),detail('Subject exacto y grafo',JSON.stringify(prepared,null,2)));$('approve-confirm').textContent=`Confirmar aprobación QA como ${view.operator}`;$('approve-confirm').onclick=()=>task(async()=>{await command({op:'qa-approve',targetId,subjectSha256:prepared.subjectSha256},prepared.version);$('approval').close();});$('approval').showModal();}
function renderNew(){const root=$('detail');root.append(el('h2','Crear requisito'),el('p','Registrá el pedido tal como lo conocés. Las dudas se trabajan después, sin inventar respuestas.','muted'));
  const title=field(root,'Título del requisito'),description=field(root,'Pedido o descripción','','textarea'),source=field(root,'Fuente conocida (opcional)');
  root.append(button('Guardar borrador',async()=>{await command({op:'create',title:title.value,description:description.value,source:source.value});selected=view.history[0].event.targetId;render();}));}
function criteriaEditor(root,criteria){const rows=[];const list=el('div');root.append(el('h3','Criterios de aceptación'),list);
    function add(c){const box=el('div',undefined,'card');const fields=el('div',undefined,'criteria');box.append(fields);const given=field(fields,'Dado',c?.given??'','textarea'),when=field(fields,'Cuando',c?.when??'','textarea'),then=field(fields,'Entonces',c?.then??'','textarea');const row={id:c?.id??`ac-${crypto.randomUUID()}`,given,when,then,removed:false};rows.push(row);box.append(button('Quitar criterio',async()=>{markDirty(selected);row.removed=true;box.remove();},true));list.append(box);}
  for(const c of criteria)add(c);root.append(button('Agregar criterio',async()=>{markDirty(selected);add();},true));return ()=>rows.filter(r=>!r.removed).map(r=>({id:r.id,given:r.given.value,when:r.when.value,then:r.then.value}));}
function renderRequirement(a){const root=$('detail');root.append(el('h2',a.title),el('p',`${labels[a.status]} · revisión ${a.revision}`,'muted'));
  const approval=view.approvals.filter(r=>r.targetId===a.id).at(-1);if(approval)root.append(el('p',approval.valid?'Aprobación vigente para este contexto.':'La aprobación anterior ya no cubre el contexto actual. Revisá y guardá una nueva revisión antes de aprobar.','notice'));
  const title=field(root,'Título',a.title),description=field(root,'Descripción del requisito',a.content.description,'textarea');const criteria=criteriaEditor(root,a.content.acceptanceCriteria);
  const actions=el('div',undefined,'actions');root.append(actions);
  actions.append(button('Guardar nueva revisión',async()=>command({op:'edit',targetId:a.id,title:title.value,content:{description:description.value,acceptanceCriteria:criteria()}})),button('Revisar aprobación',()=>openApproval(a.id),true));
  if(a.status==='approved'||a.status==='active')actions.append(button('Preparar propuesta SpecDD',async()=>command({op:'prepare-projection',targetId:a.id}),true));
  renderProjections(root,a);
  root.append(el('h3','Trabajar con el agente'),el('p','El agente analiza la última revisión guardada. Guardá tus cambios antes de continuar. Enviar contexto puede consumir cuota del proveedor configurado.','muted'));
  const consentLabel=el('label',undefined,'check'),consent=document.createElement('input');consent.type='checkbox';consentLabel.append(consent,el('span','Autorizo enviar este contexto al agente configurado para esta acción.'));root.append(consentLabel);
  const agentActions=el('div',undefined,'actions');root.append(agentActions);
  for(const [name,action] of [['Analizar requisito','analyze-requirement'],['Refinar redacción','refine-wording'],['Sugerir criterios','suggest-acceptance-criteria']]){
    const b=button(name,async()=>{if(dirty)throw new Error('UNSAVED_CHANGES');if(!consent.checked)throw new Error('RUNTIME_CONSENT_REQUIRED');await api(`${base()}/runs`,{version:view.version,request:{targetId:a.id,action,consent:true}});await refresh();},true);b.disabled=!view.runtimeAvailable||view.runs.some(r=>r.status==='running');agentActions.append(b);
  }
  if(!view.runtimeAvailable)root.append(el('p','Agente no configurado. Podés crear, editar y revisar localmente; el operador debe habilitar el runtime.','notice'));
  for(const run of view.runs.filter(r=>r.targetId===a.id))renderRun(root,run);
  root.append(el('h3','Preguntas y reglas relacionadas'));
  const linked=new Set(view.graph.edges.filter(e=>e.from===a.id||e.to===a.id).flatMap(e=>[e.from,e.to]));
  const related=view.artifacts.filter(t=>t.id!==a.id&&linked.has(t.id));
  if(!related.length)root.append(el('p','No hay preguntas o reglas incorporadas. Esto no demuestra que el requisito esté completo.','muted'));
  for(const item of related){const box=el('div',undefined,'card');box.dataset.artifact=item.id;box.append(el('h3',item.title),el('p',`${labels[item.status]} · revisión ${item.revision}`,'muted'));
    if(item.type==='open-question'){box.append(el('p',item.content.blocking?'Bloquea aprobación mientras no tenga respuesta.':'Pregunta no bloqueante.'));const answer=field(box,'Respuesta humana',item.content.resolution?.answer??'','textarea');box.append(button('Guardar respuesta humana',async()=>command({op:'resolve-question',targetId:item.id,answer:answer.value})));}
    else if(item.type==='business-rule'){const statement=field(box,'Regla propuesta',item.content.statement,'textarea'),rationale=field(box,'Motivo',item.content.rationale,'textarea');box.append(button('Guardar revisión de regla',async()=>command({op:'edit',targetId:item.id,title:item.title,content:{statement:statement.value,rationale:rationale.value}}),true),button('Revisar aprobación de regla',()=>openApproval(item.id),true));}
    else box.append(el('p',JSON.stringify(item.content)));root.append(box);
  }
  const impact=view.graph.impact[a.id].nodes.filter(n=>n.artifactId!==a.id);root.append(el('p',`Impacto conocido: ${impact.length} artefacto(s) dependiente(s). Sólo relaciones del contexto registrado. No es una evaluación completa del negocio.`,'muted'));
  root.append(detail('Historial de este requisito y procedencia',view.histories[a.id].map(r=>`Revisión ${r.revision} · ${labels[r.status]}\n${r.content.description}\nOrigen: ${r.provenance.map(p=>`${p.actor.id} (${p.origin})`).join(' → ')}`).join('\n\n')));
}
function renderProjections(root,a){
  const projections=view.projections.filter(p=>p.proposal.source.artifact.artifactId===a.id),canonicals=view.canonicalSpecs.filter(c=>c.source.artifact.artifactId===a.id);
  if(!projections.length&&!canonicals.length)return;
  root.append(el('h3','Proyección gobernada a SpecDD'));
  for(const entry of projections){const p=entry.proposal,status=entry.status==='proposed'?'Propuesta pendiente':entry.status==='applied'?'Aplicada':'Descartada',box=el('div',undefined,'card projection');box.append(el('h3',`${p.destination.path} · ${status}`),el('p',`Mapping ${p.mapping.status==='partial'?'parcial':'completo'} · ${p.mapping.incomplete.length} faltante(s) · ${p.mapping.unsupported.length} no soportado(s)`,'muted'),detail('Contenido propuesto',p.content),detail('Diff exacto',p.diff),detail('Reporte de mapping',JSON.stringify(p.mapping,null,2)),detail('Trazabilidad de propuesta',JSON.stringify({...p.source,destination:p.destination,contentSha256:p.contentSha256},null,2)));
    if(entry.status==='proposed')box.append(button('Revisar y crear artefacto SpecDD',()=>openProjectionApproval(p.id)),button('Descartar propuesta SpecDD',async()=>command({op:'discard-projection',projectionId:p.id}),true));root.append(box);}
  for(const c of canonicals){const box=el('div',undefined,'card canonical');box.append(el('h3',`Artefacto SpecDD canónico · ${c.path}`),el('p',`Revisión ${c.revision} · hash ${c.contentSha256}`,'muted'),detail('Contenido canónico',c.content),detail('Trazabilidad canónica',JSON.stringify(c.source,null,2)));root.append(box);}
}
function renderRun(root,run){const box=el('div',undefined,'card proposal');box.append(el('h3',labels[run.status]),el('p',`${run.action} · ${new Date(run.startedAt).toLocaleString()}`,'muted'));
  if(run.error)box.append(el('p',errors[run.error]??run.error));
  if(run.status==='running')box.append(button('Cancelar análisis',async()=>{await api(`${base()}/cancel`,{runId:run.id});await refresh();},true));
  if(run.proposal){const out=run.proposal.output;const checks=[];box.append(el('p','Propuesta del agente: no es una decisión ni una aprobación. Seleccioná sólo lo que querés incorporar como borrador.'));
    for(const a of out.ambiguities)box.append(el('p',`Observación: ${a.description}`));
    const suggestions=[...(out.wording?[{...out.wording,text:`Redacción: ${out.wording.description}`}]:[]),...out.questions.map(s=>({...s,text:`Pregunta: ${s.question} (${s.blocking?'bloqueante':'no bloqueante'})`})),...out.rules.map(s=>({...s,text:`Regla propuesta: ${s.statement}\nMotivo: ${s.rationale}`})),...out.criteria.map(s=>({...s,text:`Criterio: Dado ${s.given}, cuando ${s.when}, entonces ${s.then}`}))];
    for(const s of suggestions){const l=el('label',undefined,'check'),c=document.createElement('input');c.type='checkbox';c.disabled=run.status!=='ready';l.append(c,el('span',s.text));box.append(l);checks.push({id:s.id,c});}
    if(run.status==='ready'){box.append(button('Incorporar seleccionadas',async()=>command({op:'adopt',runId:run.id,selectedIds:checks.filter(s=>s.c.checked).map(s=>s.id)})),button('Descartar propuesta',async()=>command({op:'discard',runId:run.id}),true));}
  }
  box.append(detail('Evidencia de ejecución',JSON.stringify({id:run.id,requestSha256:run.requestSha256,runtime:run.runtime},null,2)));root.append(box);
}
async function openApproval(targetId){let artifact=view.artifacts.find(a=>a.id===targetId);
  if(dirty)throw new Error('UNSAVED_CHANGES');
  if(artifact.status==='draft'){await command({op:'request-review',targetId});artifact=view.artifacts.find(a=>a.id===targetId);}
  const prepared=await api(`${base()}/approval?target=${encodeURIComponent(targetId)}`);
  $('approval-title').textContent='Revisar aprobación exacta';$('approval-note').textContent='No modifica ni publica una spec. Si cambia el contexto, la aprobación deberá revisarse.';
  $('approval-content').replaceChildren(el('h3',artifact.title),el('p',`Revisión ${artifact.revision} · revisor: ${view.operator}`),el('pre',JSON.stringify(artifact.content,null,2)),detail('Subject exacto y grafo',JSON.stringify(prepared,null,2)));
  $('approve-confirm').textContent=`Confirmar aprobación como ${view.operator}`;
  $('approve-confirm').onclick=()=>task(async()=>{await command({op:'approve',targetId,subjectSha256:prepared.subjectSha256},prepared.version);$('approval').close();});$('approval').showModal();
}
async function openProjectionApproval(projectionId){if(dirty)throw new Error('UNSAVED_CHANGES');const entry=view.projections.find(p=>p.proposal.id===projectionId),p=entry?.proposal;if(!p||entry.status!=='proposed')throw new Error('PROJECTION_NOT_FOUND');
  const subjectSha256=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(canonical(p))).then(b=>[...new Uint8Array(b)].map(v=>v.toString(16).padStart(2,'0')).join(''));
  $('approval-title').textContent='Revisar proyección SpecDD exacta';$('approval-note').textContent='La confirmación crea el artefacto canónico sólo en el store local. No escribe archivos, Git ni publica.';
  $('approval-content').replaceChildren(el('h3',p.destination.path),el('p',`Mapping ${p.mapping.status} · revisor: ${view.operator}`),detail('Diff exacto',p.diff),detail('Faltantes y no soportados',JSON.stringify({incomplete:p.mapping.incomplete,unsupported:p.mapping.unsupported},null,2)),detail('Contenido completo',p.content),detail('Subject exacto',JSON.stringify({subjectSha256,proposal:p},null,2)));
  $('approve-confirm').textContent=`Crear artefacto SpecDD como ${view.operator}`;$('approve-confirm').onclick=()=>task(async()=>{await command({op:'apply-projection',projectionId,subjectSha256});$('approval').close();});$('approval').showModal();
}
function canonical(value){if(value===null||typeof value==='boolean'||typeof value==='string'||typeof value==='number')return JSON.stringify(value);if(Array.isArray(value))return `[${value.map(canonical).join(',')}]`;return `{${Object.keys(value).sort().map(k=>`${JSON.stringify(k)}:${canonical(value[k])}`).join(',')}}`;}
$('detail').addEventListener('input',event=>{if(event.target.type!=='checkbox')markDirty(event.target.closest('[data-artifact]').dataset.artifact);});
errors.UNSAVED_CHANGES='Tenés cambios sin guardar. Guardá la revisión antes de analizar, actualizar o aprobar.';
errors.RUNTIME_CONSENT_REQUIRED='Marcá el consentimiento de envío de contexto para ejecutar esta acción.';
$('approve-cancel').onclick=()=>$('approval').close();$('new').onclick=()=>{if(dirty){message(new Error('UNSAVED_CHANGES'));return;}selected=null;render();};$('refresh').onclick=()=>task(refresh);
$('ba-mode').onclick=()=>{if(dirty){message(new Error('UNSAVED_CHANGES'));return;}role='ba';selected=null;$('ba-mode').className='';$('qa-mode').className='secondary';render();};
$('qa-mode').onclick=()=>{if(dirty){message(new Error('UNSAVED_CHANGES'));return;}role='qa';selected=null;$('qa-mode').className='';$('ba-mode').className='secondary';render();};
$('projects').onchange=()=>task(async()=>{if(dirty){$('projects').value=projectId;throw new Error('UNSAVED_CHANGES');}projectId=$('projects').value;selected=null;await refresh();});
task(async()=>{session=await api('/api/session');const data=await api('/api/projects');for(const p of data.projects){const o=el('option',p.name);o.value=p.id;$('projects').append(o);}projectId=data.projects[0]?.id;if(projectId)await refresh();else $('detail').append(el('p','No hay proyectos preparados. El operador debe registrar un bundle revisado.','empty'));});
