import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { compareBenchmark, fingerprint } from '@specdd/benchmarks';
import { assessProposal, reviewState } from '../dist/index.js';

const read = p => readFileSync(new URL(p, import.meta.url), 'utf8');
const json = p => JSON.parse(read(p));
const normalized = p => read(p).replaceAll('\r\n', '\n').trim();
assert.equal(normalized('./compiled/index.js'), normalized('./candidate/index.js'), 'Compiled candidate differs from measured snapshot');
assert.equal(normalized('../dist/index.js').replace('../schema/proposal.schema.json', '../../schema/proposal.schema.json'), normalized('./candidate/index.js'), 'Production build differs from measured candidate');
assert.equal(normalized('../src/index.ts').replace('../schema/proposal.schema.json', '../../schema/proposal.schema.json'), normalized('./source/index.ts'), 'Production source differs from approved candidate');
const proposal = json('./proposal.json');
const plan = json('./evidence/plan.json'), dataset = json('./evidence/dataset.json');
assert.deepEqual(compareBenchmark(plan, dataset), json('./evidence/report.json'));
const bundle = { proposal, sourcePlan: plan, sourceDataset: dataset, plan, dataset };
const assessment = assessProposal(bundle);
const journal = json('./journal.json');
assert.equal(assessment.eligibleForReview, true);
const review = reviewState(bundle, journal);
assert.ok(['approved', 'pr-recorded'].includes(review.state));
const handoff = json('./pr-handoff.json');
assert.equal(handoff.proposalSha256, fingerprint(proposal));
assert.equal(handoff.assessmentSha256, review.assessmentSha256);
const approval = journal.find(event => event.action === 'approved');
assert.ok(approval);
assert.equal(handoff.reviewHeadSha256, fingerprint(approval));
assert.deepEqual(handoff.target, proposal.target);
assert.equal(handoff.createdPR, false);
console.log(JSON.stringify({ assessment, review, localSource: 'matches-approved-candidate', recordedPR: review.prUrl }, null, 2));
